In [1]:
import numpy as np 
l = [1,2,3]
a = np.array([1,2,3])

In [2]:
a

array([1, 2, 3])

In [3]:
l

[1, 2, 3]

In [27]:
for e in l:
    print (e)

1
2
3


In [28]:
for e in a:
    print(e)

1
2
3


> to add to list we can use append but not possible in numpy

In [8]:
l.append(4)

In [9]:
l

[1, 2, 3, 4]

In [10]:
a.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [11]:
l = l + [5]

In [12]:
l

[1, 2, 3, 4, 5]

In [13]:
a = a + [5]

In [14]:
a

array([6, 7, 8])

In [15]:
a = a + [5,4]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

> we cannot add anything to a numpy array

In [4]:
l2 = []
for e in l:
    l2.append(e+e)

In [5]:
l2

[2, 4, 6]

3

In [6]:
a+a #( numpy arry uses matrix addition)

array([2, 4, 6])

In [7]:
a

array([1, 2, 3])

In [8]:
2*a

array([2, 4, 6])

In [11]:
2*l # repeated two time in numpy for dongt he above cal we need to loop

[1, 2, 3, 1, 2, 3]

In [13]:
l**2 # cannot power the list 

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [14]:
a**2

array([1, 4, 9])

In [15]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [16]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [17]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

<ul>
    <li>If wanted to do above computations with list we need do  for loop individually</li>
    <li>if we want to represent vector numpy array is convinent to add,multiply,square</li>
    <li>list too are good, we can treat list as array</li>
    <li>numpy we can treat as a vector a math object</li>
    <li>to do opration on list we need for loop, for loops are very slow and we need to avoid during math operations.</li>
</ul>
