In [2]:
import numpy as np
n = np.array([1,2,3])

In [5]:
z = np.zeros([10]) # arrays of all zeros vector

In [6]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
#Matrix of zeros 
m = np.zeros([10,10])

In [8]:
m

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
one = np.ones([10,10])

In [11]:
one

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [37]:
np.random.random((10,10)) # this give uniform distributed number between 1 to 0

array([[0.99071722, 0.55621899, 0.79606275, 0.86385123, 0.66435348,
        0.66318362, 0.8513961 , 0.35569158, 0.7534836 , 0.03621495],
       [0.63084739, 0.6316473 , 0.39381558, 0.9090096 , 0.66742229,
        0.4536838 , 0.15459169, 0.62588243, 0.01731338, 0.88495606],
       [0.07229992, 0.69779801, 0.22424665, 0.72284641, 0.05815484,
        0.94945467, 0.00429668, 0.69020856, 0.73216193, 0.75248154],
       [0.00107665, 0.22889645, 0.44346473, 0.21080501, 0.83681858,
        0.35235378, 0.4168283 , 0.23722067, 0.65729227, 0.36853173],
       [0.46493596, 0.43411802, 0.59778533, 0.06875444, 0.04349273,
        0.83287312, 0.07587559, 0.39674997, 0.05075317, 0.6701908 ],
       [0.27798119, 0.76718261, 0.98870828, 0.83040274, 0.11998615,
        0.2318966 , 0.65534068, 0.65756807, 0.74964523, 0.81926829],
       [0.66883963, 0.6815029 , 0.73005258, 0.04373016, 0.71702059,
        0.25408455, 0.13178315, 0.71182952, 0.60409754, 0.31266868],
       [0.88306534, 0.01910292, 0.3331361

In [47]:
#guasian distributed 
g= np.random.randn(10,10)

In [48]:
g.mean()

0.13826275052677975

In [49]:
g.std()

0.9602897291347339

In [50]:
g.var()

0.9221563638816606