numpy can be used for 
> Maths & logigal  operation

> fourier transforms

>linear algebra operations

In [3]:
import numpy as np
x = np.array([2,3,'n',4])

In [6]:
print(type(x))

<class 'numpy.ndarray'>


> generate linspace 

np.linspace(start,stop,num,dtype,retstep)
> start of interval range,
> stop end of interval range,
> num number of sampels to be generated,

In [11]:
b = np.linspace(start=1,stop=10,num=10,endpoint= True,retstep= False)

In [12]:
b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

a= np.arange(start,stop,step) 

In [14]:
a= np.arange(start=1,stop=10,step=2) 

In [16]:
a

array([1, 3, 5, 7, 9])

In [23]:
np.ones((3,4)) # 3= rows & 4 = col

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.random.rand(5)

array([0.43504566, 0.37373632, 0.28489944, 0.38910888, 0.28158866])

In [29]:
np.random.rand(5,2)

array([[0.41226039, 0.46237096],
       [0.58930292, 0.38643711],
       [0.01944116, 0.41793727],
       [0.71414716, 0.85668554],
       [0.00240439, 0.13107222]])

np.logspace(start=1,stop=10,num=50(default),endpoint= True,base=10)

In [32]:
np.logspace(start=1,stop=10,num=5,endpoint= True,base=10)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [33]:
z=range(1000)

In [35]:
timeit sum(z)

20 µs ± 207 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [36]:
x = np.array(z)

In [38]:
timeit np.sum(x)

4.89 µs ± 30 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [39]:
getsizeof()
itemsize

NameError: name 'getsizeof' is not defined

In [40]:
import sys

In [41]:
sys.getsizeof(1)*len(x)

28000

In [44]:
x.itemsize*x.size

8000

> reshape an array

> numpy operation

> access an element 

#### resahpe()  recasts an array to new shape without changing data 

In [48]:
grid = np.arange(start=1,stop=10).reshape(3,3)

In [49]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
# array dimension 
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
b = np.arange(start=11,stop=20).reshape(3,3)

In [53]:
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [55]:
np.add(a,b) # addition

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [56]:
np.multiply(a,b)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [63]:
np.subtract(a,b)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [62]:
np.divide(a,b)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [61]:
np.remainder(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

> array can be accessed  using index number

In [64]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
a[0]

array([1, 2, 3])

In [66]:
# extract index with inex (0,1)

In [67]:
a[0,1]

2

In [68]:
# second and third row for a

In [69]:
a[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [70]:
# first col a
a[:,0]

array([1, 4, 7])

In [72]:
# extract element from first row 
a[0,:]

array([1, 2, 3])

> subset form orginal array

In [75]:
# subset 2*2 array 
# first two rows and colums from a


In [77]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [78]:
# changing the subset value 

In [79]:
a[0,0] = 12

In [80]:
a

array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

> modefying the arry using transpose function 
np.transpose()

In [82]:
# interchange rows or colum

In [84]:
np.transpose(a)

array([[12,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9]])

In [85]:
#modifying array using append()

In [86]:
a_row = np.append(a,[[10,12,13]],axis = 0)

In [87]:
a_row

array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 12, 13]])

In [88]:
col = np.array([23,14,13]).reshape(3,1)

In [89]:
col

array([[23],
       [14],
       [13]])

In [90]:
a_col = np.append(a,col,axis=1)

In [91]:
a_col

array([[12,  2,  3, 23],
       [ 4,  5,  6, 14],
       [ 7,  8,  9, 13]])

In [92]:
# modifying array using insert()
#np.inster(array,ob,values,axis)

In [94]:
a_ins= np.insert(a,1,[13,15,16],axis=0)

In [96]:
a_ins

array([[12,  2,  3],
       [13, 15, 16],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [97]:
# modefying arrays using delete(a,2,axis=0)

In [103]:
del_a = np.delete(a,0, axis=0)

In [104]:
del_a

array([[4, 5, 6],
       [7, 8, 9]])

> Matrix 
<ol>
    <li>create matrices</li>
    <li>dimensions</li>
    <li>Modifying matrices</li>
    <li>acessing elements of matrics</li>
    <li>Matrix operations</li>
</ol>

In [105]:
# matrix 2 dimensisonal data structure consisting of numbers and columns

In [106]:
# row runs horizonally and col urns vertically 

In [107]:
#3*3, 3*1, 1*3[1,2,3]

In [108]:
#np.matrix(data)

In [113]:
a=np.matrix("1,2,3,4;4,5,6,7;7,8,9,10")

In [115]:
a

matrix([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]])

In [116]:
a.shape

(3, 4)

In [119]:
a.shape[0]

3

In [120]:
a.shape[1]

4

In [121]:
a.size

12

In [122]:
#modfiying using insert()

In [123]:
#np.insert(matrix,obj,values,axis)

In [174]:
row_new = np.matrix("2,3,4,5")

In [175]:
row_new

matrix([[2, 3, 4, 5]])

In [176]:
row_new.shape

(1, 4)

In [177]:
#a=np.insert(1,0,col_new,axis=0)

In [179]:
a1 = np.insert(a,0,row_new,axis=0)

In [180]:
a1

matrix([[ 2,  3,  4,  5],
        [ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]])

In [181]:
# modifying using index number 
#row = 1 , col 1  changing the number 2

In [182]:
a1[1,1]=12

In [183]:
a1

matrix([[ 2,  3,  4,  5],
        [ 1, 12,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]])

In [184]:
#extract from second row of matrix a
print(a[1,:])

[[4 5 6 7]]


In [188]:
a1[:,1]

matrix([[ 3],
        [12],
        [ 5],
        [ 8]])

In [241]:
# matrix addition
A = np.matrix(np.arange(0,20)).reshape(5,4)

In [242]:
A

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [243]:
B = np.matrix(np.arange(20,40)).reshape(5,4)

In [244]:
B

matrix([[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]])

In [245]:
A+B

matrix([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])

In [246]:
print(np.add(A,B))

[[20 22 24 26]
 [28 30 32 34]
 [36 38 40 42]
 [44 46 48 50]
 [52 54 56 58]]


In [247]:
np.subtract(A,B)

matrix([[-20, -20, -20, -20],
        [-20, -20, -20, -20],
        [-20, -20, -20, -20],
        [-20, -20, -20, -20],
        [-20, -20, -20, -20]])

In [248]:
np.divide(A,B)

matrix([[0.        , 0.04761905, 0.09090909, 0.13043478],
        [0.16666667, 0.2       , 0.23076923, 0.25925926],
        [0.28571429, 0.31034483, 0.33333333, 0.35483871],
        [0.375     , 0.39393939, 0.41176471, 0.42857143],
        [0.44444444, 0.45945946, 0.47368421, 0.48717949]])

In [249]:
np.multiply(A,B)

matrix([[  0,  21,  44,  69],
        [ 96, 125, 156, 189],
        [224, 261, 300, 341],
        [384, 429, 476, 525],
        [576, 629, 684, 741]])

In [250]:
np.dot(A,B)

ValueError: shapes (5,4) and (5,4) not aligned: 4 (dim 1) != 5 (dim 0)

In [251]:
#np.dot(A,B) # while doing matrix multiplication the rows and colum should be aligned thats same e.g 5*%
# to get the propera alignment we can do a transpose 

In [252]:
B= np.transpose(B)

In [253]:
B

matrix([[20, 24, 28, 32, 36],
        [21, 25, 29, 33, 37],
        [22, 26, 30, 34, 38],
        [23, 27, 31, 35, 39]])

In [254]:
np.dot(A,B)

matrix([[ 134,  158,  182,  206,  230],
        [ 478,  566,  654,  742,  830],
        [ 822,  974, 1126, 1278, 1430],
        [1166, 1382, 1598, 1814, 2030],
        [1510, 1790, 2070, 2350, 2630]])

> Linear Algebra opearations
<ol>
    <li>determinants of matrix</li>
    <li>rank of matrix</li>
    <li>Inverse of matrix</li>
    <li>solving equations<li>
</ol>

In [255]:
#np.linalg.det(matrix)

In [257]:
x = np.matrix("2,3,4,5;-2,3,4,5;4,5,6,7;9,8,5,8")

In [258]:
x

matrix([[ 2,  3,  4,  5],
        [-2,  3,  4,  5],
        [ 4,  5,  6,  7],
        [ 9,  8,  5,  8]])

In [260]:
det_m=np.linalg.det(x)

In [261]:
det_m

-47.999999999999986

In [262]:
#rank of matrix (find the liner independent linearly independent col)

In [264]:
rank_matrix = np.linalg.matrix_rank(x)

In [265]:
rank_matrix

4

In [267]:
#inverse of matrix (returs a multipclivative inv of matrix)

In [268]:
np.linalg.inv(x)

matrix([[ 2.50000000e-01, -2.50000000e-01, -9.86864911e-17,
          2.46716228e-17],
        [-1.50000000e+00,  4.16666667e-01,  5.83333333e-01,
          1.66666667e-01],
        [-1.25000000e+00, -8.33333333e-02,  1.33333333e+00,
         -3.33333333e-01],
        [ 2.00000000e+00, -8.33333333e-02, -1.41666667e+00,
          1.66666667e-01]])

In [269]:
c = np.matrix("2,1,2;1,0,1;3,1,3")

In [270]:
c

matrix([[2, 1, 2],
        [1, 0, 1],
        [3, 1, 3]])

In [271]:
det_s = np.linalg.det(c)

In [272]:
det_s

0.0

In [275]:
# in case of det of = 0 the inve gives a singualar matrix

In [276]:
np.linalg.inv(c)

LinAlgError: Singular matrix

In [277]:
# sys of linear equ

In [279]:
3x+y+2z=2
3x+2y+5z= -1
6x+7y+8z=3

SyntaxError: invalid syntax (<ipython-input-279-e9b29a0232a6>, line 1)

In [281]:
#Ax=b solve x= Ainv.b

In [284]:
#np.linalg.solve(matA,matB) # solves ax= b

In [292]:
n = np.matrix("5,3,6;2,4,4;5,4,3")

In [293]:
n

matrix([[5, 3, 6],
        [2, 4, 4],
        [5, 4, 3]])

In [294]:
b= np.matrix("2,-1,3").transpose()

In [295]:
b

matrix([[ 2],
        [-1],
        [ 3]])

In [296]:
n_sol = np.linalg.solve(n,b)

In [297]:
n_sol

matrix([[ 1.18],
        [-0.38],
        [-0.46]])